name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
            build_type: Release
            name: "Windows MSVC"
            vcpkg_triplet: x64-windows
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            build_type: Release
            name: "Linux GCC"
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
            build_type: Release
            name: "Linux Clang"

    steps:
    - uses: actions/checkout@v4

    - name: Install SFML (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y libsfml-dev

    - name: Install vcpkg and SFML (Windows)
      if: runner.os == 'Windows'
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.bat -disableMetrics
        ./vcpkg install sfml:${{ matrix.vcpkg_triplet }} --recurse
      shell: pwsh # PowerShell is good for these Windows commands

    - name: Set reusable strings
      id: strings
      shell: bash # bash is fine for echo and GITHUB_OUTPUT
      run: |
        # github.workspace on Windows is like D:\a\repo\repo. Appending /build makes it D:\a\repo\repo/build
        # CMake handles mixed slashes well. The key is quoting these paths when used in bash commands later.
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          echo "artifact-output-dir=${{ github.workspace }}/build/${{ matrix.build_type }}" >> "$GITHUB_OUTPUT"
        else
          echo "artifact-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
        fi

    - name: Configure CMake (Windows)
      if: runner.os == 'Windows'
      # Using bash, so paths (especially those with backslashes from github.workspace) must be quoted.
      shell: bash
      run: >
        cmake -B "${{ steps.strings.outputs.build-output-dir }}"
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake"
        -DVCPKG_TARGET_TRIPLET=${{ matrix.vcpkg_triplet }}
        -S "${{ github.workspace }}"

    - name: Configure CMake (Linux)
      if: runner.os == 'Linux'
      # Quoting paths is good practice everywhere, though less critical for typical Linux paths.
      shell: bash
      run: >
        cmake -B "${{ steps.strings.outputs.build-output-dir }}"
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S "${{ github.workspace }}"

    - name: Build
      # Quoting the build directory path.
      shell: bash
      run: cmake --build "${{ steps.strings.outputs.build-output-dir }}" --config ${{ matrix.build_type }}

    - name: List build artifacts (for debugging)
      if: always()
      shell: bash
      run: |
        echo "Listing content of build directory: ${{ steps.strings.outputs.build-output-dir }}"
        ls -R "${{ steps.strings.outputs.build-output-dir }}" || echo "Build output directory not found or empty."
        echo "Expected artifact output directory: ${{ steps.strings.outputs.artifact-output-dir }}"
        ls -R "${{ steps.strings.outputs.artifact-output-dir }}" || echo "Artifact output directory not found or empty."

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }}-${{ matrix.build_type }}-Build-Output-${{ runner.os }}
        path: ${{ steps.strings.outputs.artifact-output-dir }}
        if-no-files-found: warn
